name: AI Pasif Gelir Otomatik Blog

# Repoya okuma/yazma izni
permissions:
  contents: write

on:
  # Her Pazartesi 03:00 UTC’de çalışacak
  schedule:
    - cron: '0 3 * * 1'
  # Manuel tetikleme imkanı
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: true
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Auto Blog Script
        run: python auto_blog.py
